name: Auto Crawler NexaNova

on:
  schedule:
    - cron: '*/5 * * * *' # Si avvia ogni 5 minuti
  workflow_dispatch: # Permette anche l'avvio manuale dalla scheda Actions

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Imposta Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installa le dipendenze
        run: npm install

      - name: Esegui Crawler
        env:
          TURSO_URL_1: ${{ secrets.TURSO_URL_1 }}
          TURSO_TOKEN_1: ${{ secrets.TURSO_TOKEN_1 }}
        run: node crawler.js
